In [104]:
import pandas as pd
from scipy.io import arff
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

In [3]:
file_name = "risco_treinamento_covid.csv"
df = pd.read_csv(file_name)
print('Data loaded')

Data loaded


In [4]:
x_train = df.drop('risk', axis=1)
y_train = df['risk']

In [5]:
model = LogisticRegression(max_iter=10000)
model.fit(x_train, y_train)

LogisticRegression(max_iter=10000)

In [6]:
file_name = "risco_teste_de_resultado_covid.csv"
df = pd.read_csv(file_name)
print('Test data loaded')

Test data loaded


In [42]:
x_test = df.drop('risk', axis=1)
y_test = df['risk']

In [23]:
model.score(x_test, y_test)

0.8796

In [9]:
filename = 'predict_risk_model.pkl'
pickle.dump(model, open(filename, 'wb'))
print("Model saved")

Model saved


In [24]:
y_pred = model.predict(x_test)

In [68]:
#y_pred

In [71]:
#x_train

idade  fumante  obeso  doenca_pulmonar  nivel_sintomas
0         54        1      0                0               1
1         78        1      0                0               2
2          6        0      1                1               2
3         75        0      1                1               3
4         32        0      0                1               1
...      ...      ...    ...              ...             ...
39995     69        0      0                1               4
39996     18        1      1                0               0
39997     25        0      1                0               2
39998     70        0      1                1               3
39999      9        1      1                1               3

[40000 rows x 5 columns]

In [66]:
#y_train

In [84]:
feature_cols = ['idade', 'fumante', 'obeso', 'doenca_pulmonar', 'nivel_sintomas']

In [85]:
#sns.pairplot(df, x_vars=['idade', 'fumante', 'obeso', 'doenca_pulmonar', 'nivel_sintomas'], y_vars='risk', height=10, aspect=0.7, kind="reg")

In [95]:
X = df[feature_cols]

In [98]:
Y = df['risk']

In [99]:
y

array([0, 0, 1, ..., 1, 1, 0])

In [102]:
print(x_train.shape)

(40000, 5)


In [103]:
print(y_train.shape)

(40000,)


In [108]:
plt.plot(x_test, y_pred)

In [109]:
model.coef_

array([[-0.80806975, -8.640187  , -8.77211844, -8.68247914, -8.81771467],
       [ 0.11949833, -0.67674418, -0.71495342, -0.71515164, -0.5935842 ],
       [ 0.26988784,  2.31994764,  2.3370081 ,  2.3778353 ,  2.14193667],
       [ 0.41868358,  6.99698354,  7.15006375,  7.01979548,  7.2693622 ]])

In [111]:
model.intercept_

array([ 32.92780955,   9.05606811,  -4.56351047, -37.42036719])